### ISSUE TITLE
Docs recipe not working in 0.18.1

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq#515]
After the update, it seems that the docs recipe is broken. 

I tried creating a new site with `wyam new -r Docs` and when running the wyam build without any modifications, i got the following error: 
```
    Executing pipeline "BlogIndexes" (5/21) with 1 child module(s)
                    Exception while processing document file:///C:/Users/kevin/.nuget/packages/Wyam.Docs.Samson.0.18.1/content/_BlogIndex.cshtml in module Razor: One or more compilation failures occurred:
/_Navbar.cshtml(12,71): error CS0103: The name 'BookSiteKeys' does not exist in the current context
                    Error while executing module Razor
                Error while executing module ModuleCollection
            Error while executing module If
        Error while executing pipeline BlogIndexes
```

**Comment by daveaglick** [comment]
You probably just broke some kind of record for release to bug report time. Looking at it now - existing docs build, so might be something strange with the scaffolding.

**Comment by daveaglick** [comment]
Thanks for catching that so early. You mess up one little cut-and-paste and it all goes to hell :). Publishing 0.18.2 now...
